apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "mern-socket-service"
spec:
  tls:
    - hosts:
        - ide.enterprise.com
      secretName: ide-tls-cert
  rules:
    - host: ide.enterprise.com
      http:
        paths:
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: mern-socket-service
                port:
                  number: 5000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: mern-api-service
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mern-api-service
                port:
                  number: 5000
